version: "2"
services:
  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  app:
    build: ./web/user_crud/
    links:
      - db
    ports:
      - "5000:5000"
    extra_hosts:
      - "cmbpde160:10.17.73.49"